//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，如果
//     代码重新生成，这些更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodProcurementSystem.Admin {
    public partial class Login {
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Label lblError;
    }
}